import asyncio
import random
from typing import AsyncGenerator

class DummyEngine:
    def __init__(self, mode: str, model_id: str):
        self.mode = mode
        self.model_id = model_id

    async def chat_stream(self, prompt: str) -> AsyncGenerator[str, None]:
        # Dummy streaming mock
        response_tokens = f"This is a response generated by SovereignAI using {self.model_id} in {self.mode} mode.".split()
        for token in response_tokens:
            yield token + " "
            await asyncio.sleep(random.uniform(0.01, 0.1))

class EngineFactory:
    @staticmethod
    def get_engine(mode: str, model_id: str) -> DummyEngine:
        # In a real app we'd load memory and C bindings here based on modes
        if mode == "fullram":
            # Real code would spawn fullram inference C-binding
            return DummyEngine("fullram", model_id)
        elif mode == "layerstream":
            # Real code would spawn layer stream scheduler
            return DummyEngine("layerstream", model_id)
        else:
            raise ValueError(f"Unknown mode {mode}")
